# Site settings
title: Scala Downunder
description: "Scala Downunder brings together the Scala Australasian community offering a program of keynote presentations, expert guest speakers, and informal networking with fellow developers."
baseurl: ""
url: "scaladownunder.org"
future: false

# Build settings
markdown: kramdown
permalink: pretty
include: ['.nojekyll']
exclude: ['bower_components', 'node_modules', '_gulp', 'resources/scripts', 'resources/styles', 'resources/icons', 'bower.json', 'package.json', 'gulpfile.js', 'README.md']
